# Generated by Django 2.0.dev20170322162159 on 2017-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_has_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_has_tag',
            name='t_id',
            field=models.ManyToManyField(to='movies.Tag'),
        ),
    ]
