# Generated by Django 2.0.dev20170322162159 on 2017-04-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_has_tag_t_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=15)),
                ('m_id', models.ManyToManyField(to='movies.Movie')),
            ],
        ),
    ]
