# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20170414_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_middle_name',
            new_name='middle_name',
        ),
    ]
