# Generated by Django 2.0.dev20170322162159 on 2017-04-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20170414_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_has_tag',
            name='m_id',
        ),
        migrations.RemoveField(
            model_name='movie_has_tag',
            name='t_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='m_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='u_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Review'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=models.ManyToManyField(to='movies.Tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='review',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Review'),
        ),
        migrations.DeleteModel(
            name='Movie_Has_Tag',
        ),
    ]
