# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20170414_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crew',
            old_name='c_first_name',
            new_name='crew_first_name',
        ),
        migrations.RenameField(
            model_name='crew',
            old_name='c_last_name',
            new_name='crew_last_name',
        ),
    ]
