# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20170415_1301'),
        ('movies', '0017_auto_20170415_1308'),
    ]

    operations = [
    ]
