# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20170416_1829'),
        ('movies', '0020_auto_20170416_1827'),
    ]

    operations = [
    ]
