# Generated by Django 2.0.dev20170322162159 on 2017-04-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20170416_1829'),
        ('movies', '0020_auto_20170416_1843'),
    ]

    operations = [
    ]
