# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_merge_20170416_1909'),
        ('movies', '0021_merge_20170416_1855'),
    ]

    operations = [
    ]
